source/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import index
from likes.views import likes
from task.views import task_detail, task_list
from rating.views import rating
from userman.views import userman
from categories.views import  categories_list, category_detail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url (r'^$', index),
    url (r'^likes/$', likes),
    url(r'^rating/$', rating),
    url(r'^task/', include ('task.urls', namespace='task')),
    url(r'^userman/', userman),
    url(r'^categories/',include ('categories.urls', namespace='categories')),
    url(r'^', include ('core.urls', namespace='core')),

]

source/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.views import RegisterFormView,LoginFormView,LogoutView

urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

source/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

source/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from core.models import User
from django.shortcuts import render,HttpResponse
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm as OldUserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from django.views.generic.base import View
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class UserCreationForm(OldUserCreationForm):
    class Meta:
        model = User
        fields = ('username', )



class TrueRegister(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(TrueRegister, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'зарегистрироваться'))


class RegisterFormView(FormView):
    form_class = TrueRegister

    success_url = reverse_lazy("core:login")

    template_name = "core/register.html"



    def form_valid(self, form):

        form.save()
        return super(RegisterFormView, self).form_valid(form)


def index (request):
    return HttpResponse ('This is index')


class TrueLogin (AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super(TrueLogin,self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit','войти'))


class LoginFormView (FormView):
    form_class = TrueLogin

    template_name = "core/login.html"

    success_url = reverse_lazy("categories:categories_list")

    def form_valid(self, form):

        self.user = form.get_user()

        login(self.request, self.user)
        return super (LoginFormView, self).form_valid(form)

class LogoutView(View):
    def get(self, request):
        logout(request)

        return HttpResponseRedirect(reverse_lazy("core:login"))

source/core/templates/core/base.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "bootstrap-4.1.1/favicon.ico" %}">

    <title> {% block title %}TaskSolver{% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap-4.1.1/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    {% block CUSTOME_STYLES %}{% endblock %}
    <link href="{% static "bootstrap-4.1.1/docs/4.1/examples/sticky-footer-navbar/sticky-footer-navbar.css" %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <a class="navbar-brand" href="#">TaskSolver</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav ml-auto">
                  {% if user.is_authenticated  %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:logout" %}">Выйти</a>
                      </li>
                  {% else %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:login" %}">Войти</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:register" %}">Зарегестрироваться</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
        {% block content %}
            Default content
        {% endblock %}
    </main>

    <footer class="footer">
        {% block footer %}
        <div class="container">
            <span class="text-muted">@Copyleft Maslov Roman TaskSolver</span>
        </div>
        {% endblock %}
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "bootstrap-4.1.1/assets/js/vendor/jquery-slim.min.js" %}"></script>
    <script src="{% static "bootstrap-4.1.1/assets/js/vendor/popper.min.js" %}"></script>
    <script src="{% static "bootstrap-4.1.1/dist/js/bootstrap.min.js" %}"></script>
  </body>
</html>

source/core/templates/core/login.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Вход на сайт {% endblock %}


{% block content %}
    <h3>Вход на сайт</h3>
    <form class="" action="" method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
{%  endblock %}

source/core/templates/core/register.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Регистрация {% endblock %}


{% block content %}
    <h3>Регистрация</h3>
    <form class="" action="" method="post">
        {% csrf_token %}
        {% crispy form %}
     </form>
{%  endblock %}