source/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import index
from likes.views import likes
from task.views import task_detail, task_list
from rating.views import rating
from userman.views import userman
from categories.views import  categories_list, category_detail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url (r'^$', index),
    url (r'^likes/$', likes),
    url(r'^rating/$', rating),
    url(r'^task/', include ('task.urls', namespace='task')),
    url(r'^userman/', userman),
    url(r'^categories/',include ('categories.urls', namespace='categories')),
    url(r'^', include ('core.urls', namespace='core')),

]

source/categories/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from categories.views import  categories_list, category_detail, CategoryEdit, CategoryCreate

urlpatterns = [

    url(r'^$', categories_list, name='categories_list'),
    url(r'^(?P<pk>\d+)/detail/$', category_detail, name='category_detail'),
    url(r'^(?P<pk>\d+)/edit/$', CategoryEdit.as_view(), name='category_edit'),
    url(r'^create/$', CategoryCreate.as_view(), name = 'category_create'),

]

source/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.views import RegisterFormView,LoginFormView,LogoutView

urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

source/task/urls.py
from django.conf.urls import url
from django.contrib import admin

from task.views import task_list,task_detail, TaskCreate, TaskEdit

urlpatterns = [

    url(r'^$', task_list, name='task_list'),
    url(r'^(?P<pk>\d+)/detail/$', task_detail, name='task_detail'),
    url(r'^(?P<pk>\d+)/edit/$', TaskEdit.as_view(), name='task_edit'),
    url(r'^create/$', TaskCreate.as_view(), name='task_create'),
]

source/task/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from categories.models import Category
from core.models import User
# Create your models here.


class Task(models.Model):

    auth = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='tasks',
        verbose_name=u'Автор'
    )
    categories = models.ManyToManyField(Category, blank=True, related_name='tasks', verbose_name=u'Категории')
    name = models.CharField(max_length=255, verbose_name=u'Имя задания')
    is_finished = models.BooleanField(default=False, verbose_name=u'Задание завершено')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    prescription = models.TextField(max_length=4096, verbose_name=u'Описание')
    usertask = models.ManyToManyField(User, blank=True, related_name='users', verbose_name=u'Пользователи')

    class Meta:
        verbose_name = u'Задание'
        verbose_name_plural = u'Задания'
        ordering = 'name', 'id'

    def __unicode__(self):
        return self.name

source/task/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse, get_object_or_404
from .models import Task

from comments.models import Comment

from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.views.generic import UpdateView,CreateView
# Create your views here.
def task_list(request):

    context = {
        'tasks': Task.objects.all()
    }

    return render(request, 'tasks/tasks_list.html', context)


def task_detail(request, pk=None):

    task = get_object_or_404(Task, id=pk)

    if request.method == 'GET':
        task.usertask.add(request.user)
        task.save()
    if request.method == 'POST':
        if request.POST['type'] == 'comment':
            comment = Comment()
            comment.text = request.POST['comment']
            comment.author = request.user
            comment.task_id = pk
            comment.save()
            task.task_comments.add(comment)
            task.save()
        elif request.POST['type'] == 'close':
            task.is_finished = True
            task.save()
    context = {
        'task': task,
        'comments': Comment.objects.all().filter(task=task),

    }
    return render(request, 'tasks/tasks_detail.html', context)


class TaskEdit (UpdateView):
    model = Task
    fields = 'name',
    context_object_name = 'task'
    template_name = 'tasks/tasks_edit.html'


    def get_success_url(self):
        return reverse('task:task_detail', kwargs={'pk': self.object.pk})


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name','prescription','categories']

    def __init__(self,*args,**kwargs):
        super(TaskForm,self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit','Сохранить'))




class TaskCreate(CreateView):
    form_class = TaskForm
    context_object_name = 'task'
    template_name = 'tasks/tasks_create.html'

    def form_valid(self, form):
        form.instance.auth = self.request.user
        return super(TaskCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('task:task_detail', kwargs={'pk': self.object.pk})

source/task/templates/tasks/tasks_create.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Создание задания {% endblock %}


{% block content %}
     <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href ={% url "task:task_list" %}>Назад</a></p>
        </div>
    </div>
    <h3>Создание Задания</h3>

    {% crispy form %}
{%  endblock %}

source/task/templates/tasks/tasks_detail.html
{% extends "core/base.html" %}


{%  block content %}
    <a href="{% url "categories:categories_list"  %}">Back</a>

    <div class = "row">
        <div class="col-md-12">
             <h3>Название задания: {{ task.name }}</h3>

                 <p class = "p-1"><a class="float-left" href = "{%  url "task:task_edit" pk=task.id %}">Редактировать название</a></p>
                 <p class = "p-1">{{ task.prescription }}</p>

            <h3>Комментарии:</h3>
        </div>
        {%  for current_comment in comments %}
            <div class="col-md-12">
                <div class ="card card-block bg-faded mt-2">
                    <p class = "p-1">{{ current_comment.author.username }} : {{ current_comment.text }}</p>
                    <p class = "p-1">{{ current_comment.created }}</p>
                </div>
            </div>
        {% endfor %}
        <form action="" method = "post">
                {% csrf_token %}
                <input type="submit" value='Добавить комментарий'>
                <input type="text" name="comment">
                <input type="text" value='comment' hidden name = 'type'>
                </form>
        <br>
        {% for user in task.usertask.all %}
            <div class="col-md-12">
                <div class ="card card-block bg-faded mt-2">
                    <p class = "p-1"> Задание взял:  {{ user.username }} </p>
                </div>
            </div>
        {% endfor %}


        <br>
        {% if task.is_finished == True %}
            Задание завершено, всем спасибо!

        {% elif task.is_finished == False%}
            <form action="" method = "get">
            {% csrf_token %}
            <input type="submit" value='Взять задание'>
            </form>

            <br>
             {% if user.is_superuser %}
                <form action="" method = "post">
                {% csrf_token %}
                <input type="submit" value='Закрыть задание'>
                <input type="text" value='close' hidden name = 'type'>
                </form>
            {% endif %}

        {%  endif%}


    </div>
{% endblock %}

source/task/templates/tasks/tasks_edit.html
{% extends "core/base.html" %}

{% block content %}
    <form action="" method = "post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="редактировать">
    </form>
{%  endblock %}

source/task/templates/tasks/tasks_list.html
{% extends "core/base.html" %}


{% block content %}
    <h3>Категории заданий</h3>
    <div class="row">
        {% for task in tasks %}
            <div class="col-md-12">
                <div class = "card">
                    <div class="card-body">
                    <a href="{% url "task:task_detail" pk=task.id %} ">{{ task.name }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        {{  username }}
    </div>
{%  endblock %}