source/application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import index
from likes.views import likes
from task.views import task_detail, task_list
from rating.views import rating
from userman.views import userman
from categories.views import  categories_list, category_detail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url (r'^$', index),
    url (r'^likes/$', likes),
    url(r'^rating/$', rating),
    url(r'^task/', include ('task.urls', namespace='task')),
    url(r'^userman/', userman),
    url(r'^categories/',include ('categories.urls', namespace='categories')),
    url(r'^', include ('core.urls', namespace='core')),

]

source/categories/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from categories.views import  categories_list, category_detail, CategoryEdit, CategoryCreate

urlpatterns = [

    url(r'^$', categories_list, name='categories_list'),
    url(r'^(?P<pk>\d+)/detail/$', category_detail, name='category_detail'),
    url(r'^(?P<pk>\d+)/edit/$', CategoryEdit.as_view(), name='category_edit'),
    url(r'^create/$', CategoryCreate.as_view(), name = 'category_create'),

]

source/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.views import RegisterFormView,LoginFormView,LogoutView

urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view(), name='register'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

source/task/urls.py
from django.conf.urls import url
from django.contrib import admin

from task.views import task_list,task_detail, TaskCreate, TaskEdit

urlpatterns = [

    url(r'^$', task_list, name='task_list'),
    url(r'^(?P<pk>\d+)/detail/$', task_detail, name='task_detail'),
    url(r'^(?P<pk>\d+)/edit/$', TaskEdit.as_view(), name='task_edit'),
    url(r'^create/$', TaskCreate.as_view(), name='task_create'),
]

source/categories/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(max_length=4096, verbose_name=u'Описание')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created date')
    updated = models.DateTimeField(auto_now=True,verbose_name='Updated date')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        ordering = 'name', 'id'

source/categories/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404
from .models import Category
from django import forms
from django.views.generic import UpdateView,CreateView
from django.urls import reverse_lazy
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
# Create your views here.


class CategoriesListForm (forms.Form):

    sort = forms.ChoiceField(choices=(
        ('name', "Name asc"),
        ('-name', 'Name desc'),
        ('id', 'ID'),
    ), required= False)
    search = forms.CharField(required=False)


def categories_list(request):

    categories = Category.objects.all()
    if request.method == 'GET':
        form = CategoriesListForm(request.GET)
        if form.is_valid():
            data = form.cleaned_data
            if data['sort']:
                categories = categories.order_by(data['sort'])
            if data['search']:
                categories = categories.filter(name__icontains=data['search'])

        context = {
            'categories': categories,
            'form': form,
        }
        return render(request, 'categories/categories_list.html', context)

    elif request.method == 'POST':
        return HttpResponseRedirect(reverse_lazy("core:login"))





class CategoryEdit (UpdateView):

    model = Category
    fields = 'name',
    context_object_name = 'category'
    template_name = 'categories/category_edit.html'


    def get_success_url(self):
        return reverse('categories:category_detail', kwargs={'pk': self.object.pk})


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name','description']

    def __init__(self,*args,**kwargs):
        super(CategoryForm,self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit','Сохранить'))


class CategoryCreate(CreateView):
    form_class = CategoryForm
    context_object_name = 'category'
    template_name = 'categories/category_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CategoryCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('categories:category_detail', kwargs={'pk': self.object.pk})


def category_detail(request, pk=None):

    category = get_object_or_404(Category, id=pk)

    context = {
        'category': category,
        'tasks': category.tasks.all().filter(is_finished=False)
    }
    return render(request, 'categories/category_detail.html', context)

source/categories/templates/categories/base_categories.html
{% extends "core/base.html" %}

{% block title %}This is categories part of site{% endblock %}

source/categories/templates/categories/categories_list.html
{% extends "core/base.html" %}

{% block title %} Категории - {{ block.super }} {% endblock %}
{% block content %}
    <a class = "btn btn-primary float-right" href="{% url "categories:category_create"%}">Создать новую</a>

    <h3>Категории заданий</h3>

    <div class="row mb-2">
        <form action="" method = "get">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="col">
                        {{ form }}
                        <input type="submit" value="search">
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-12">
                <div class ="card card-block bg-faded mt-2">
                    <p class="p-1"><a class="card-link" href="{% url "categories:category_detail" pk=category.id %} "> {{ category.name }}</a></p>
                    <p class="p-1">{{ category.description }}</p>
                    <p class="p-1"><a class="float-right" href = "{%  url "categories:category_edit" pk=category.id %}">Редактировать название</a></p>
                </div>
            </div>
        {% endfor %}

    </div>

{%  endblock %}

source/categories/templates/categories/category_create.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Создание категории - {{ block.super }}{% endblock %}




{% block content %}
    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href ={% url "categories:categories_list" %}>Назад</a></p>
        </div>
    </div>
    <h3>Создание Категории</h3>

    {% crispy form %}
{%  endblock %}

source/categories/templates/categories/category_detail.html
{% extends "categories/base_categories.html" %}

{%  block content %}
   <a href="{% url "categories:categories_list" %}">Назад</a>
    <br>
   <h3>Категория: {{ category.name }}</h3>

    <div class ="row">
        {% for task in tasks %}
            <div class="col-md-12">
                <div class ="card card-block bg-faded mt-2">
                    <p class = "p-1"><a class="card-link" href="{% url "task:task_detail" pk=task.id %}">{{ task }}</a></p>
                    <p class = "p-1"><i class="float-right"> {{ task.created|date:"Y-m-d" }}</i></p>
                </div>
            </div>
        {% endfor %}

    </div>
    <br>
    <br>
    <a href="{% url "task:task_create" %}">Создать новое задание</a>
{% endblock %}

source/categories/templates/categories/category_edit.html
{% extends "core/base.html" %}

{% block content %}
    <form action="" method = "post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="редактировать">
    </form>
{%  endblock %}